name: ImapBook_Discussions_Classification
channels:
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0
  - astor=0.8.1
  - blas=1.0
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - click=7.1.2
  - cycler=0.10.0
  - freetype=2.10.4
  - gast=0.2.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - importlib-metadata=2.0.0
  - intel-openmp=2019.4
  - joblib=1.0.0
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libedit=3.1.20191231
  - libffi=3.3
  - libmklml=2019.0.5
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - markdown=3.3.3
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - ncurses=6.2
  - ninja=1.10.2
  - nltk=3.5
  - olefile=0.46
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - pillow=8.1.0
  - pip=20.3.3
  - protobuf=3.13.0.1
  - pycparser=2.20
  - pyparsing=2.4.7
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.5
  - readline=8.0
  - regex=2020.11.13
  - setuptools=51.3.3
  - six=1.15.0
  - sqlite=3.33.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - attrs==20.3.0
    - babel==2.9.0
    - blis==0.2.4
    - boto3==1.16.59
    - botocore==1.19.59
    - cachetools==4.2.1
    - catalogue==1.0.0
    - chardet==4.0.0
    - conllu==1.3.1
    - cymem==2.0.5
    - docutils==0.16
    - editdistance==0.5.3
    - filelock==3.0.12
    - flaky==3.7.0
    - flask==1.1.2
    - flask-cors==3.0.10
    - ftfy==5.8
    - future==0.18.2
    - gevent==21.1.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - greenlet==1.0.0
    - idna==2.10
    - imagesize==1.2.0
    - iniconfig==1.1.1
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonnet==0.17.0
    - jsonpickle==1.5.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - murmurhash==1.0.5
    - numpy==1.18.3
    - numpydoc==1.1.0
    - oauthlib==3.1.0
    - overrides==3.1.0
    - packaging==20.8
    - pandas==1.0.3
    - parsimonious==0.8.1
    - plac==0.9.6
    - pluggy==0.13.1
    - preshed==2.0.1
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.7.4
    - pytest==6.2.1
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pyyaml==5.3.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - responses==0.12.1
    - rsa==4.7
    - s3transfer==0.3.4
    - sacremoses==0.0.43
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - sentencepiece==0.1.95
    - snowballstemmer==2.1.0
    - spacy==2.1.9
    - sphinx==3.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.4.1
    - srsly==1.0.5
    - tensorboard==2.1.1
    - tensorboardx==2.1
    - tensorflow==2.1.1
    - tensorflow-estimator==2.1.0
    - thinc==7.0.8
    - tokenizers==0.7.0
    - toml==0.10.2
    - torch==1.5.0
    - torchvision==0.6.0
    - tqdm==4.46.0
    - transformers==2.9.1
    - unidecode==1.1.2
    - urllib3==1.26.2
    - wasabi==0.8.1
    - wcwidth==0.2.5
    - word2number==1.1
    - xlrd==1.2.0
    - zope-event==4.5.0
    - zope-interface==5.2.0